### ISSUE TITLE
Disable touch on cover, customize gesture action

### ISSUE THREAD

**Issue by NeuroNex** [Ph1b/MaterialAudiobookPlayer#335] opened 2015-10-19 00:43 UTC
Hi,

Using Material Audiobook Player 2.4.2 on Lollipop 5.11, Moto G 2014.

Is it possible to add a setting to disable the action when touching on the cover? Currently it pause/play on touch. The cover take the majority of the screen. Somehow, I made quite often unintentional touch on the cover and trigger accidentally the pause/play.

Even better, if you work on gesture on the cover. It would be a killer feature if you allow the user to select the action on each swipe (up, down, left, right). For example: swipe up = volume up, swipe down = volume down.

Hope you would consider the feature.

Regards

**Comment by kevmitch** [comment] 2015-10-19 07:31
duplicate of #254

**Comment by NeuroNex** [comment] 2015-10-27 00:27
I have read in #254 that the feature is intended and the thread was closed. I understand the decision and I confirm that the majority of audio player I have tried so far also have that feature (tap on cover = pause/play). This is good for people using the app when driving.

However, please allow me to insist. Not everybody drives while using the app, In those cases a lot of interaction such as review track list, album list, skipping etc. On a phone with 5+ inches in size, and with a cover taking the majority of the screen, the accidental touch to the cover is really non-negligible. All you need is just to make this optional and 100% of people will be happy. Take your time, but please don't discard this idea. I also hate complex player with a millions of settings. But this, I believe is a useful option.

**Comment by Ph1b** [comment] 2015-12-02 15:44
I rethought this and decided to enforce a long-click on the cover to toggle play / pause.

**Closed by Ph1b** 2015-12-02 15:44 UTC

**Comment by Targren** [comment] 2015-12-24 22:16
Is there any chance we can convince you to rethink the rethinking, and give us the option, for the sake of us frequent road-trippers?
