### ISSUE TITLE
Add Volume Boost

### ISSUE THREAD

**Issue by NeuroNex** [Ph1b/MaterialAudiobookPlayer#334] opened 2015-10-19 00:33 UTC
Hi,
Using Material Player 2.4.2 on Lollipop 5.1.1, Moto G 2014

This player is now almost perfect. However, I cannot use it in noisy environment (bus and subway transit). In those situations I switch to other audiobook players which has a volume boost feature. This allows to boost (multiply?) the system volume. Can you please add this feature? Thanks very much in advance.

Below is how volume boost is implemented on some other audiobook players:

![audiobook_volumeboost](https://cloud.githubusercontent.com/assets/10089894/10567617/760f6eb4-75d7-11e5-8cb7-04110552d829.png)

**Comment by kevmitch** [comment] 2015-10-19 07:27
duplicate of #223

**Closed** 2015-10-25 20:57 UTC
