### ISSUE TITLE
Add media rescan function

### ISSUE THREAD

**Issue by NeuroNex** [Ph1b/MaterialAudiobookPlayer#212] opened 2015-06-01 17:36 UTC
Using 2.1.9.1 on Android 4.44. I have set the Audiobook folder to one located on the SDcard (/storage/sdcard1/MyAudiobooks). Please note that this Audiobook master folder has a .nomedia file.

When I installed Material Audio the 1st time. All books were recognized OK. Then I added 4 more books (each book is a subdir with relevant MP3s). On two of these books, only two tracks were recognized. Using another media player or audiobook player, the tracks are recognized completely.

Using Material Audiobook settings. Removing the Audiobook directory. Exit MA, Restart MA, add the same Audiobook directory back. Solves the issue.

May be a Media Rescan function would be more convenient to fix the cataloging issue.

**Comment by Ph1b** [comment] 2015-06-03 00:40
This is not necessary because the player should detect updates in books automatically. What you faces was a bug where it dit not do this properly.

This should be fixed as of 788d5d28c48086401e9144e99c5e8e7c01105918

Please test if this works as intended now:
https://github.com/Ph1b/MaterialAudiobookPlayer/blob/master/distribute/66-develop-preview1.apk

**Comment by kevmitch** [comment] 2015-06-03 08:41
Oh, cool. I was going to mention this at some point. Fix works great here for adding a new audiobook.

However, deleting sometimes works and is sometimes sketchy.  In the sketchy cases, it does not seem to remove the book in question from the list at first, but continually gives a "defect file" warning on arriving at the bookshelf screen.  Eventually, it recognizes that the files is gone and actually removing the book from the list. I'm not really sure what triggers this, but it seems to only happen when I add my whole /sdcard/Audiobooks folder with about 10 books in it. If I create a test folder with a couple books, adding and removing individual books seems to work mostly fine.

Finally, it seems that it doesn't recognize if I have changed the file metadata such as "Album" or cover art. I have to actually delete the book and re-add it for these types of changes to be recognized.

**Comment by kevmitch** [comment] 2015-06-05 04:52
With recent commits, I'm no longer seeing the "defect file" problem. 

It does however still take quite a while (a minute or more) before it recognizes that there's a new book or that one is removed. Metadata updates are also still undetected.

**Comment by Ph1b** [comment] 2015-06-05 18:48
The thing causing this problems is, is that the media scanner (called "BookAdder") is a really brutal guy. He is just making a loong list of the books and files to add and is working trough. If someone says: Hey, we deleted an audiobook here, then he'll just drop all the progress and start from scratch.

Im working on a way to make this more sophisticated. My current abstract is as follows.

````java
    public synchronized void init() {
        removeRedundantAudiobookDirs(collectionBooks, singleBooks);
        removeNotExistingBooks(collectionBooks, singleBooks);
        addOrUpdateBooks(collectionBooks, singleBooks);
        startWatching(collectionBooks, singleBooks);
    }
````

Which basically means that there is a defined process:

1. All books no longer belonging to user-chosen-folders get hidden.
2. All Audiobooks inside the audiofolders that simply do not physically exist get hidden.
3. Books that are not in the list get added, books that have updates get updated
4. A FileWatcher for each Book is set up which will trigger directly 3. when there are changes on the file layer.

That way will ensure minimum work load and a instant re-check if books have been modified.

**Closed** 2015-06-09 19:10 UTC
Labels: bug, more information needed
