### ISSUE TITLE
Final seconds of audio file skipped

### ISSUE THREAD

**Issue by Lawpoint** [Ph1b/MaterialAudiobookPlayer#192] opened 2015-05-23 03:13 UTC
I often hear that the very last piece of an audio file is not played - the player proceeds to the next file, clipping the end of the previous one. About 0.5 - 1.5 seconds are _sometimes_ skipped. This happens in maybe 40% of all track advances. However, if I rewind back and listen to the same audio again, the issue is often _not_ reproduced.

LG Nexus 4, stock Android 5.1.

**Comment by Ph1b** [comment] 2015-05-24 15:30
So conclusion is that the onCompletionListener is fired too early then. The problematic part should be [here](https://github.com/Ph1b/MaterialAudiobookPlayer/blob/v2.1.7/audiobook/src/main/java/de/ph1b/audiobook/mediaplayer/CustomMediaPlayer.java#L463).
Someone has to look into it, I don't really understand the audio processing.

**Comment by Ph1b** [comment] 2015-06-23 19:49
Duplicate of #53

**Closed by Ph1b** 2015-06-23 19:49 UTC
Labels: bug, help needed
