### ISSUE TITLE
Thumbnails do not correspond to books

### ISSUE THREAD

**Issue by honzzz** [Ph1b/MaterialAudiobookPlayer#243] opened 2015-06-28 16:09 UTC
Thumbnails are mixed up, they do not correspond to books. I tried to delete application data but when I added the audiobook folder again, all books got loaded with incorrect images again. I made sure that correct images are placed in correct folders.

**Comment by Ph1b** [comment] 2015-06-28 16:16
Does it still exist when you really uninstall and install the app again?

**Comment by honzzz** [comment] 2015-06-28 16:28
Uninstalling and re-installing helped. I have one folder with podcasts and other folder with multiple audiobooks, each in separate subfolder. I think that I deleted some books and added some other books to that folder yesterday - could that be the cause? How does the app rescan the folder when its content changes? Is there some recommended way how to store content so the app can handle it without re-installing?
Thank you for your quick help.

**Comment by Ph1b** [comment] 2015-06-28 21:33
duplicate of #238

**Comment by Ph1b** [comment] 2015-06-28 21:34
Its a onetime bug which wont be fixed and should only have happened when upgrading from the previous version. If this ever happens again please report immediately. Thx :)

**Closed by Ph1b** 2015-06-28 21:33 UTC
