### ISSUE TITLE
Show book duration

### ISSUE THREAD

**Issue by kgraefe** [Ph1b/MaterialAudiobookPlayer#227] opened 2015-06-16 07:20 UTC
I have an audiobook with one file per chapter. Is there any way to see the duration of the whole book and how long it is to the end?

In the slider I'd really like to see the duration of the whole book. I don't care about the chapters length. ;)

**Comment by Ph1b** [comment] 2015-06-23 19:41
Duplicate of #202

**Comment by Ph1b** [comment] 2015-06-23 19:45
Approved. When I find time, I will implement a fading shadow from the bottom of the cover and display the total time and played time there in white.

**Comment by Ph1b** [comment] 2015-08-13 10:50
I quote my previous mail with skynetua here:

> I like the way the sleep timer is implemented. On the global progress: I kind of like the way it works now and that its not bloating the interface. But after thinking a while about it, I think it is not a good UX concept to have hidden features. Users would click on it by accident and then of cause see how it works. Even though that can be nice under certain circumstances, this approach leads to „geek“ software like the VLC interface. It has millions of features but people tend to just use play and pause as everything else is so intransparent.
So it would be better to have a simple static view showing the progress without the way to change it manually.

Where he asked
> I'm not sure I understood you correctly. You proposed just to disable seekbar or remove it at all and leave only 2 textviews without layout hiding?

My answer:
Yes, that's exactly what I meant.

**Comment by skynetua** [comment] 2015-08-13 10:51
disable or remove?
:)

**Comment by Ph1b** [comment] 2015-08-13 11:02
Remove ;)

**Comment by Queven** [comment] 2015-08-19 19:47
I also think that the duration of the whole book is good idea. I'm really looking forward to this feature.

**Comment by nioncode** [comment] 2015-08-23 13:57
Looking forward to this, sounds great :)

**Comment by skynetua** [comment] 2015-08-24 15:07
Which mockup would you prefer:
[Mockup A](https://cloud.githubusercontent.com/assets/3670941/9443565/5d9003e4-4a8a-11e5-88c1-e91c56f791aa.png)
[Mockup B](https://cloud.githubusercontent.com/assets/3670941/9443570/664d10f8-4a8a-11e5-913d-6b6fa5f2e007.png)

Or maybe A without chapter number?

**Comment by nioncode** [comment] 2015-08-24 16:30
I like A much better. Also, I would keep the chapter number in place.

The floating rectangle in B looks out of place, wheras in A it looks like the entire information stacks on top of the cover art, which is more inline with the Material Design language.

**Comment by Queven** [comment] 2015-08-24 17:10
I think A better with chapter number.

**Comment by Ph1b** [comment] 2015-08-24 20:43
A is way less distractive. But without the chapter progress, due to less visual clutter. Thanks for the engagement!

**Comment by Ph1b** [comment] 2015-09-11 08:48
Implemented as of v2.4.0

**Closed by Ph1b** 2015-09-11 08:48 UTC
Labels: feature approved

**Comment by nioncode** [comment] 2015-09-12 17:19
Was this replaced with the book progress in the overview layout? 
I would much rather have the option to see the overall progress of the current book while playing a single chapter without having to go back to the overview Activity. 

Can we add this back as an optional setting?

**Comment by Ph1b** [comment] 2015-09-12 17:25
I preferred this due to less visual clutter. The new layout did not fit in so well.

**Comment by nioncode** [comment] 2015-09-13 13:42
I think the overlay over the album cover does fit in quite good and provides easier feedback, because it is not necessary to go back to the overview to see the progress of the current book. 
The overlay could be toggled with a touch on the album art. Currently this toggles playback, but this is not intuitive anyway.

Another option would be to replace the seek bar for the current track with a seek bar for the entire book and add the chapter marks as ticks on the seek bar. This would reduce the 'clutter', but keep all the functionality.

**Comment by Ph1b** [comment] 2015-09-13 17:43
I maybe think of it some day. The ticks on the seekbar won't be a sulution because that would make navigating with > 100 tracks a real pain.
